spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    url: jdbc:h2:mem:pay
  jpa:
    hibernate:
      naming:
        physical-strategy: ru.cns.util.jpa.hibernate.CustomPhysicalNamingStrategy
      ddl-auto: create
    open-in-view: false
